name: trojan ipk
on: push
env:
  FILE: openwrt-sdk-19.07.3-ramips-mt7620_gcc-7.5.0_musl.Linux-x86_64
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - name: 1
      run: |
        sudo apt-get update
        sudo apt-get install subversion build-essential libncurses5-dev zlib1g-dev gawk git ccache gettext libssl-dev xsltproc wget unzip python time libcloog-isl-dev
    - name: 2
      run: |
        wget https://downloads.openwrt.org/releases/19.07.3/targets/ramips/mt7620/openwrt-sdk-19.07.3-ramips-mt7620_gcc-7.5.0_musl.Linux-x86_64.tar.xz
        tar xvf openwrt-sdk*
        cd $FILE
        git clone https://github.com/trojan-gfw/openwrt-trojan.git package/trojan
        git clone https://github.com/aa65535/openwrt-dns-forwarder.git package/dns-forwarder
    - name: 3
      run: |
        cd $FILE
        make package/symlinks
        ./scripts/feeds update -a
        ./scripts/feeds install -a
    - name: Setup Debug Session
      uses: P3TERX/debugger-action@master
    - name: 5
      run: |
        cd $FILE
        make package/trojan/compile V=s
        make package/dns-forwarder/compile V=s
    - name: Upload bin directory
      uses: actions/upload-artifact@master
      if: steps.compile.outputs.status == 'success' && env.UPLOAD_BIN_DIR == 'true'
      with:
        name: OpenWrt_directory
        path: $FILE/bin

    - name: Organize files
      id: organize
      if: env.UPLOAD_FIRMWARE == 'true' && !cancelled()
      run: |
        cd $FILE/bin/packages/mt7620/base
        echo "::set-env name=FIRMWARE::$(pwd)"
        echo "::set-output name=status::success"
    - name: Upload firmware directory
      uses: actions/upload-artifact@master
      if: steps.organize.outputs.status == 'success' && !cancelled()
      with:
        name: trojan
        path: ${{ env.FIRMWARE }}
         
